# Generated by Django 3.0.8 on 2020-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_auto_20200823_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
